### PR TITLE
fix: Added BF 4.2.9 builds

### PR DESCRIPTION
**Pull request by mbilozub**

### CODE REVIEW

**Comment by NGFPV** [comment]
I would really like to install your firmware to add Betaflight warnings to DJI goggles. I have downloaded the hex files numerous times using Google Chrome and Edge, but no matter what I do, when I click Load Firmware [Local}, Betaflight Configurator says "Hex file appears to be corrupted"and refuses to load it. BF Configurator 10.7.0 says the following are corrupt: /betaflight_4.2.9_STM32F745_e097f4ab7.hex; betaflight_4.2.8_STM32F745_norevision.hex; betaflight_4.2.9_STM32F745_e097f4ab7.hex; betaflight_4.3.0_STM32F745_norevision.hex

However, the firmware without the DJI warning addition does work from Load Firmware [Local]: betaflight_4.2.9_STM32F745.hex

Thanks for the work you have put itno thsi project. I would be very grateful if you could help me fix this!

image

image

**Comment by mbilozub** [comment]
> I would really like to install your firmware to add Betaflight warnings to DJI goggles. I have downloaded the hex files numerous times using Google Chrome and Edge, but no matter what I do, when I click Load Firmware [Local}, Betaflight Configurator says "Hex file appears to be corrupted"and refuses to load it. BF Configurator 10.7.0 says the following are corrupt: /betaflight_4.2.9_STM32F745_e097f4ab7.hex; betaflight_4.2.8_STM32F745_norevision.hex; betaflight_4.2.9_STM32F745_e097f4ab7.hex; betaflight_4.3.0_STM32F745_norevision.hex

I had no problems with that. Try downloading the entire archive, unzip and try again.

https://take.ms/u0b9R

**Comment by mbilozub** [comment]
I flashed the STM32F7X2 version on my BLADE_F7_HD, it works as expected.

**Comment by NGFPV** [comment]
Downloading the whole zip file worked. Thanks!

**Pull request merged**
